accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("login/", views.Login.as_view(), name="login"),
    path("logout/", views.Logout.as_view(), name="logout"),
    path("register/", views.Register.as_view(), name="register"),
]

blogs/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

app_name = "blogs"

urlpatterns = [
    path("create/comment/", login_required(views.CreateComment.as_view()), name="create_comment"),
    path("create/reply/", login_required(views.CreateReply.as_view()), name="create_reply"),
    path("create/bookmark/", login_required(views.CreateBookmark.as_view()), name="create_bookmark"),
    path("create/like/", login_required(views.CreateLike.as_view()), name="create_like"),
    path("<slug:slug>/", views.BlogView.as_view(), name="blog"),
    path('photo_gallery', views.photo_gallery, name='photo_gallery'),
    path('pubs', views.pubs, name='pubs'),
]

muhunsa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

# Add this it change the header of the admin panel. 
admin.site.site_header = 'ADMIN'
admin.site.index_title = 'MUK SOCIETY OF NUTRITION'

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("blogs/", include("blogs.urls")),
    path("manage/", include("management.urls")),
    path("", views.Index.as_view(), name="index"),
    path("about_us/", views.About_us.as_view(), name="about_us"),
    path("trendings/", views.Trendings.as_view(), name="trendings"),
    path("latest/", views.Latest.as_view(), name="latest"),
    path("popular/", views.Popular.as_view(), name="popular"),
    path("search/", views.Search.as_view(), name="search"),
    path("bookmark/", views.BookmarkView.as_view(), name="bookmark"),
    path("terms-and-conditions/", views.TermsAndConditions.as_view(), name="terms_and_conditions"),
    path("category/", views.CategoryView.as_view(), name="category"),
    path("category/<slug:cat>/", views.GetCategory.as_view(), name="get_category"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/models.py
from django.db import models
from accounts.models import User
from django.utils.text import slugify
from ckeditor.fields import RichTextField
from django.core.validators import FileExtensionValidator
from django.utils import timezone

# Create your models here.
class Category(models.Model):
    category = models.CharField(max_length=30, unique=True)
    slug = models.SlugField(default="", max_length=30)
    desc = models.TextField()
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.category)
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.category

class Blog(models.Model):
    slug = models.SlugField(unique=True, null=False, blank=False, max_length=100)
    title = models.CharField(max_length=100)
    desc = models.TextField()
    content = RichTextField()
    thumbnail = models.ImageField(upload_to="thumbnails/%Y/%m/%d/")
    views = models.IntegerField(default=0)
    categories = models.ManyToManyField(Category, related_name="blogs")
    is_active = models.BooleanField(default=True)
    is_published = models.BooleanField(default=True)
    published_on = models.DateTimeField(auto_now_add=True)
    pdf_upload = models.FileField(upload_to="documents/%Y/%m/%d/", validators=[FileExtensionValidator(['pdf', 'doc', 'docx'])], null=True)
    creator = models.ForeignKey(to=User, on_delete=models.SET_NULL, related_name="blogs", null=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Blog, self).save(*args, **kwargs)

class Comment(models.Model):
    comment = models.TextField()
    likes = models.IntegerField(default=0)
    blog = models.ForeignKey(to=Blog, on_delete=models.SET_NULL, related_name="comments", null=True)
    creator = models.ForeignKey(to=User, on_delete=models.SET_NULL, related_name="comments", null=True)
    published_on = models.DateField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.comment

class Reply(models.Model):
    reply = models.TextField()
    likes = models.IntegerField(default=0)
    comment = models.ForeignKey(to=Comment, on_delete=models.SET_NULL, related_name="replies", null=True, blank=True)
    creator = models.ForeignKey(to=User, on_delete=models.SET_NULL, related_name="replies", null=True)
    published_on = models.DateField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.reply

class Bookmark(models.Model):
    blog = models.ForeignKey(to=Blog, on_delete=models.SET_NULL, related_name="bookmarks", null=True, blank=True)
    creator = models.ForeignKey(to=User, on_delete=models.SET_NULL, related_name="bookmarks", null=True, blank=True)
    created_on = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"Bookmark({self.id}, {self.creater.username})"

class BlogLike(models.Model):
    blog = models.ForeignKey(to=Blog, on_delete=models.SET_NULL, related_name="likes", null=True, blank=True)
    creator = models.ForeignKey(to=User, on_delete=models.SET_NULL, related_name="likes", null=True, blank=True)

    def __str__(self):
        return f"BlogLike({self.id}, {self.creator.username})"
    

# photo gallery
class Photo(models.Model):
    title = models.CharField(max_length=100, blank=True)
    image = models.ImageField(upload_to='photos/')
    description = models.TextField(blank=True)
    upload_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    

class Pub(models.Model):
    name = models.CharField(max_length=255, default='Unnamed')
    pdf_upload = models.FileField(upload_to="pubs/%Y/%m/%d/", validators=[FileExtensionValidator(['pdf', 'doc', 'docx'])], null=True)
    modified_date = models.DateTimeField(auto_now=True)
    size = models.PositiveIntegerField(blank=True, null=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.pk:  # Check if it's a new instance
            if self.pdf_upload:
                # Calculate and set the file size
                self.size = self.pdf_upload.size
                
        # Set the modified_date to the current East African Time
        self.modified_date = timezone.localtime(timezone.now())
        
        super().save(*args, **kwargs)

blogs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.views import View
from django.db.models import F
from django.urls import reverse
from .models import *
from django.core.paginator import Paginator
from django.shortcuts import render
from .models import Photo
from .models import Pub

# Create your views here.
def get_blog_url(slug):
    return reverse("blogs:blog", args=[slug])

class BlogView(View):
    def get(self, request, slug):
        queryset = Blog.objects.filter(is_active=True, slug=slug)
        blog = get_object_or_404(queryset)
        blog.views = F("views") + 1
        blog.save()
        blog.refresh_from_db()

        context = {
            "blog": blog,
            "comments": blog.comments.filter(is_active=True)
        }
        if request.user.is_authenticated:
            context["bookmarked"] = Bookmark.objects.filter(creator=request.user, blog=blog).first()
            context["liked"] = BlogLike.objects.filter(blog=blog, creator=request.user).first()

        return render(request, "blogs/blog.html", context)

class CreateComment(View):
    def post(self, request):
        blog = get_object_or_404(Blog.objects.filter(is_active=True, id=request.POST.get("id")))
        comment = request.POST.get("comment")
        if not comment:
            messages.warning(request, "Comment required")
            return redirect("blogs:blog", slug=blog.slug)
        c = Comment(
            comment = comment,
            creator = request.user,
            blog = blog
        )
        c.save()
        messages.success(request, "Comment created")
        return redirect(get_blog_url(blog.slug)+"#comments")

class CreateReply(View):
    def post(self, request):
        comment = get_object_or_404(Comment.objects.filter(is_active=True, id=request.POST.get("id")))
        reply = request.POST.get("reply")
        if not reply:
            messages.warning(request, "Reply required")
            return redirect("blogs:blog", slug=comment.blog.slug)

        r = Reply(
            reply = request.POST.get("reply", ""),
            comment = comment,
            creator = request.user
        )
        r.save()

        messages.success(request, "Reply created")
        return redirect(get_blog_url(comment.blog.slug)+"#comments")

class CreateBookmark(View):
    def post(self, request):
        blog = get_object_or_404(Blog.objects.filter(is_active=True, id=request.POST.get("id")))
        bookmarked = Bookmark.objects.filter(creator=request.user, blog=blog).first()
        if bookmarked:
            messages.info(request, "Already bookmarked this blog")
        else:
            b = Bookmark(
                blog = blog,
                creator = request.user
            )
            b.save()
            messages.success(request, "Bookmark created")
        return redirect("blogs:blog", slug=blog.slug)

class CreateLike(View):
    def post(self, request):
        blog = get_object_or_404(Blog.objects.filter(is_active=True, id=request.POST.get("id")))
        liked = BlogLike.objects.filter(blog=blog, creator=request.user).first()
        if liked:
            messages.info(request, "You are already liked this post")
        else:
            l = BlogLike(creator=request.user, blog=blog)
            l.save()
            messages.success(request, "Liked this blog")
        return redirect(get_blog_url(blog.slug)+"#features")
    
# photo gallery view
def photo_gallery(request):
    photos = Photo.objects.all().order_by('-upload_date')  # Newest first
    print(photos)
    paginator = Paginator(photos, 9)  # 10 photos per page
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'page_obj': page_obj}
    return render(request, 'blogs/gallery.html', context)

def pubs(request):
    resources = Pub.objects.all()  # Newest first
    context = {'resources': resources}
    return render(request, 'blogs/publication_list.html', context)

blogs/templates/blogs/blog.html
{% extends 'layout.html' %}

{% block ogtitle %}{{ blog.title }}{% endblock %}
{% block ogdescription %}{{ blog.desc }}{% endblock %}
{% block ogimage %}{{ blog.thumbnail.url }}{% endblock %}

{% block title %}Blog{% endblock %}

{% block body %}
{% load static %}
<div class="container mt-5 mb-5">
  <div class="row">
    <h2>
      {{ blog.title }}
    </h2>
  </div>
  <div class="row">
    <p>Author: {{ blog.creator }} | Views: {{ blog.views }} | Updated: {{ blog.published_on|timesince }} ago</p>
  </div>
  <div class="row mb-3">
    {% for category in blog.categories.all %}
      {% if category.is_active %}
      <div class="col">
        <a type="button" href="{% url 'get_category' category.slug %}" class="btn btn-primary btn-sm ms-auto">{{ category.category }}</a>
      </div>
      {% endif %}
    {% endfor %}
  </div>
  <div class="row">
    <div class="ratio ratio-16x9">
      <img src="{{ blog.thumbnail.url }}" class="img-fluid rounded mx-auto d-block" alt="blog's thumbnail">
    </div>
    <p>
      {{ blog.content|safe }}

      {% if blog.pdf_upload %}
      <div class="row mt-3">
        <a href="{{ blog.pdf_upload.url }}" class="btn btn-success btn-sm">Download Attached Document</a>
      </div>
        {% endif %}
    </p>

  </div>
  <br>
  <div class="row" id="features">
    <div class="col">
      {% if liked %}
      <a href="#" class="text-decoration-none">
        <i class="bi bi-hand-thumbs-up-fill"></i>
        {{ blog.likes.count }}
      </a>
      {% else %}
      <form action="{% url 'blogs:create_like' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="id" value="{{blog.id}}">
        <button type="submit" style="background:none!important;border:none;padding:0!important;" class="text-primary">
          <i class="bi bi-hand-thumbs-up"></i>
          {{ blog.likes.count }}
        </button>
      </form>
      {% endif %}
    </div>
    <div class="col">
      <a href="#comments" class="text-decoration-none">
        <i class="bi bi-chat-text"></i>
        {{ comments.count }}
      </a>
    </div>
    <div class="col">
      {% if bookmarked %}
      <a href="#" class="text-decoration-none float-end">
        <i class="bi bi-bookmark-check-fill"></i>
      </a>
      {% else %}
      <form action="{% url 'blogs:create_bookmark' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="id" value="{{blog.id}}">
        <button type="submit" style="background:none!important;border:none;padding:0!important;" class="float-end text-primary">
          <i class="bi bi-bookmark-plus"></i>
        </button>
      </form>
      {% endif %}
    </div>
    <div class="col">
      <button class="text-primary float-end" style="background:none!important;border:none;padding:0!important;" data-bs-toggle="modal" data-bs-target="#shareModal">
        <i class="bi bi-box-arrow-up"></i>
      </button>
    </div>
  </div>
  <br><br><hr>

  <div class="row mb-3" id="comments">
    <h1>
      <i class="bi bi-chat-left-text"></i>
      Comments ({{ comments.count }})
    </h1>
  </div>
  <div class="row">
    <form action="{% url 'blogs:create_comment' %}" method="post">
      {% csrf_token %}
      <input type="hidden" name="id" value="{{ blog.id }}">
      <div class="mb-3">
        <label for="comment" class="form-label">Comment:</label>
        <textarea class="form-control" id="comment" rows="3" name="comment" placeholder="Add a comment" required></textarea>
      </div>
      {% if request.user.is_authenticated %}
      <button type="submit" class="float-end btn btn-primary">
        <i class="bi bi-send"></i>
        Submit
      </button>
      {% else %}
      <a href="{% url 'accounts:login' %}" class="btn btn-primary float-end">Login</a>
      {% endif %}
    </form>
  </div>
  <br>
  <br><hr><br>
  {% for comment in comments %}
  <div class="row">
    <b>@{{ comment.creator.username }}<b>
    <span class="badge text-bg-primary">{{ comment.published_on }}</span>
    <p>{{ comment.comment }}</p>
    <a class="text-decoration-none" data-bs-toggle="collapse" href="#reply{{comment.id}}" role="button" aria-expanded="false" aria-controls="reply{{comment.id}}">
      <i class="bi bi-reply"></i>
      Reply
    </a>
    <div class="collapse" id="reply{{comment.id}}">
      <div class="card card-body">
        {% for reply in comment.replies.all %}
        <b>@{{ reply.creator.username }}<b>
        <span class="badge text-bg-primary">{{ reply.published_on }}</span>
        <p>{{ reply.reply }}</p>
        <hr>
        {% endfor %}
        <form action="{% url 'blogs:create_reply' %}" method="post">
          {% csrf_token %}
          <div class="row">
            <input type="hidden" name="id" value="{{comment.id}}">
            <div class="col-10">
              <input type="text" class="form-control" name="reply" placeholder="Add a reply" required>
            </div>
            <div class="col-2">
              <button type="submit" class="btn btn-primary">
                <i class="bi bi-send"></i>
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
  <hr>
  {% endfor %}
</div>

<div class="modal fade" id="shareModal" tabindex="-1" aria-labelledby="shareModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Share</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <button class="btn btn-primary">
          <i class="bi bi-facebook"></i>
        </button>
        <button class="btn btn-success">
          <i class="bi bi-whatsapp"></i>
        </button>
        <button class="btn btn-dark">
          <i class="bi bi-twitter-x"></i>
        </button>
        <button class="btn btn-info">
          <i class="bi bi-instagram"></i>
        </button>
        <button class="btn btn-primary">
          <i class="bi bi-telegram"></i>
        </button>
        <button class="btn btn-outline-secondary rounded-pill" id="copyBtn" onclick="copyUrl()">
          <i class="bi bi-copy"></i>
        </button>
      </div>
    </div>
  </div>
</div>

<script src="{% static 'js/blogs/blog.js' %}"></script>
{% endblock %}

blogs/templates/blogs/carousel_design.html
{% extends 'layout.html' %}

{% block title %}
  Latest
{% endblock %}

{% block body %}
  <div class="container mt-5 mb-5"> <!-- Add margin to the container -->
    <div id="carouselContainer" class="carousel-container">
      <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
          {% for photo in page_obj %}
          <div class="carousel-item {% if forloop.first %}active{% endif %}">
            <img src="{{ photo.image.url }}" class="d-block w-100 carousel-image" alt="{{ photo.title }}">
          </div>
          {% endfor %}
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
    </div>
  </div>

  <style>
    .carousel-container {
      margin: 0.5px; /* Adjust margin as needed */
    }

    .carousel-image {
      max-width: 100%; /* Ensure image width doesn't exceed parent container */
      max-height: 450px; /* Set maximum height for consistency */
      width: auto; /* Maintain aspect ratio */
      margin: auto; /* Center the image horizontally */
    }
  </style>
{% endblock %}

blogs/templates/blogs/gallery.html
{% extends 'layout.html' %}

{% block title %}
  Latest
{% endblock %}

{% block body %}
  <div class="container mt-5 mb-5">
    <div class="row row-cols-1 row-cols-md-3 g-2"> <!-- Adjust the gutter size here -->
      {% for photo in page_obj %}
        <div class="col">
          <div class="card equal-card">
            <div class="card-body">
              <img src="{{ photo.image.url }}" class="card-img-top img-fluid zoom-effect" alt="{{ photo.title }}">
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
    <!-- Pagination -->
    <nav aria-label="Photo Pagination" class="mt-4">
      <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page=1">First</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
          </li>
        {% endif %}
        {% for num in page_obj.paginator.page_range %}
          {% if page_obj.number == num %}
            <li class="page-item active"><span class="page-link">{{ num }}</span></li>
          {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
          {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
          </li>
        {% endif %}
      </ul>
    </nav>
  </div>

  <style>
    .equal-card {
      width: 100%;
      height: 300px; /* Adjust the height of the card as needed */
      display: flex;
      align-items: center;
      justify-content: center;
      border-radius: 0; /* Flat edges */
      border-color: white;
      overflow: hidden; /* Ensure the image fits within the card */
    }

    .equal-card .card-body {
      padding: 0;
    }

    .equal-size {
      width: 100%;
      height: 100%;
      object-fit: cover; /* Ensure the image covers the entire container */
      transition: transform 0.3s ease;
    }

    .zoom-effect:hover {
      transform: scale(5);
      z-index: 2; /* Bring the hovered image to the forefront */
    }
  </style>
{% endblock %}

blogs/templates/blogs/publication_list.html
{% extends 'layout.html' %}

{% block title %}
Index of {{ directory }}
{% endblock %}

{% block body %}
<div class="container mt-5 mb-5">
    <div class="row">
        <div class="col">
            <table class="table">
                <thead>
                    <tr>
                        <th>Icon</th>
                        <th>Name</th>
                        <th>Last modified</th>
                        <th>Size</th>
                        <th>Description</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><i class="bi bi-folder"></i></td>
                        <td><a href="{{ parent_directory }}">Parent Directory</a></td>
                        <td>-</td>
                        <td>-</td>
                        <td>-</td>
                    </tr>
                    {% for file in resources %}
                    <tr>
                        <td><i class="bi bi-file-earmark-text"></i></td>
                        <td><a href="{{ file.pdf_upload.url }}" download>{{ file.name }}</a></td>
                        <td>{{ file.modified_date }}</td>
                        <td>{{ file.size|filesizeformat }}</td>
                        <td>{{ file.description }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
</div>
{% endblock %}