accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("login/", views.Login.as_view(), name="login"),
    path("logout/", views.Logout.as_view(), name="logout"),
    path("register/", views.Register.as_view(), name="register"),
]

blogs/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

app_name = "blogs"

urlpatterns = [
    path("create/comment/", login_required(views.CreateComment.as_view()), name="create_comment"),
    path("create/reply/", login_required(views.CreateReply.as_view()), name="create_reply"),
    path("create/bookmark/", login_required(views.CreateBookmark.as_view()), name="create_bookmark"),
    path("create/like/", login_required(views.CreateLike.as_view()), name="create_like"),
    path("<slug:slug>/", views.BlogView.as_view(), name="blog"),
    path('photo_gallery', views.photo_gallery, name='photo_gallery'),
    path('pubs', views.pubs, name='pubs'),
]

management/urls.py
from django.urls import path
from . import views

app_name = "manage"

urlpatterns = [
    path("blog/", views.ManageBlog.as_view(), name="blog"),
    path("category/", views.ManageCategory.as_view(), name="category"),
    path("comment/", views.ManageComment.as_view(), name="comment"),

    path("create/blog/", views.CreateBlog.as_view(), name="create_blog"),
    path("create/category/", views.CreateCategory.as_view(), name="create_category"),

    path("delete/blog/<int:id>/", views.DeleteBlog.as_view(), name="delete_blog"),
    path("delete/category/<int:id>", views.DeleteCategory.as_view(), name="delete_category"),
    path("delete/comment/<int:id>", views.DeleteComment.as_view(), name="delete_comment"),

    path("edit/blog/<int:id>/", views.EditBlog.as_view(), name="edit_blog"),
    path("edit/category/<int:id>", views.EditCategory.as_view(), name="edit_category"),
]

muhunsa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

# Add this it change the header of the admin panel. 
admin.site.site_header = 'ADMIN'
admin.site.index_title = 'MUK SOCIETY OF NUTRITION'

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("blogs/", include("blogs.urls")),
    path("manage/", include("management.urls")),
    path("", views.Index.as_view(), name="index"),
    path("about_us/", views.About_us.as_view(), name="about_us"),
    path("trendings/", views.Trendings.as_view(), name="trendings"),
    path("latest/", views.Latest.as_view(), name="latest"),
    path("popular/", views.Popular.as_view(), name="popular"),
    path("search/", views.Search.as_view(), name="search"),
    path("bookmark/", views.BookmarkView.as_view(), name="bookmark"),
    path("terms-and-conditions/", views.TermsAndConditions.as_view(), name="terms_and_conditions"),
    path("category/", views.CategoryView.as_view(), name="category"),
    path("category/<slug:cat>/", views.GetCategory.as_view(), name="get_category"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/about.html
{% extends 'layout.html' %}

{% block title %}About Us{% endblock %}

{% block body %}

  <main>
    <div id="aboutUs" class="container mt-5">
      <div class="card p-4">
        <h2 class="text-center mb-4">About Makerere University Human Nutrition Students' Association (MUHUNSA)</h2>

        <!-- Location -->
        <div class="mb-4">
          <h3>Location</h3>
          <p>P.O. Box 7062,<br>
            Kampala, Uganda<br>
            Makerere University<br>
            College of Agricultural and Environmental Sciences<br>
            School of Food Technology, Nutrition and Bio-engineering<br>
            Department of Food Technology and Nutrition<br>
            MAKERERE UNIVERSITY HUMAN NUTRITION STUDENTS' ASSOCIATION (MUHUNSA)</p>
        </div>

        <!-- Social Media -->
        <!-- <div class="mb-4">
          <h3>Social Media</h3>
          <ul>
            <li>Linked in - MUHUNSA</li>
            <li>X - @Muhunsa_MAK</li>
            <li>Instagram - @muhunsa_MAK</li>
            <li>TikTok - @muhunsa_MAK</li>
            <li>Facebook - MUHUNSA</li>
            <li>Email - muhunsamakerereuniversity@gmail.com</li>
          </ul>
        </div> -->

        <!-- More Details -->
        <div class="mb-4">
          <h3>Full Disclosure</h3>
          <p>The Makerere University Human Nutrition Students' Association (MUHUNSA) is a student-led organization established to promote the welfare and academic pursuits of students studying human nutrition at Makerere University's School of Food Technology, Nutrition and Bioengineering. Our purpose is to achieve the objectives outlined in this Constitution.</p>
        </div>

        <!-- Vision -->
        <div class="mb-4">
          <h3>Vision</h3>
          <p>Our vision is to cultivate a diverse and inclusive community of future nutrition leaders, equipped with academic, professional, and personal skills to drive positive change towards a healthier and more sustainable world through safe and nutritious food access.</p>
        </div>

        <!-- Mission -->
        <div class="mb-4">
          <h3>Mission</h3>
          <p>To inspire and empower the next generation of nutrition leaders by providing a dynamic platform for academic, professional, and personal growth. We strive to create a diverse, inclusive, and collaborative community that fosters intellectual curiosity, innovative thinking, and practical skills in the field of human nutrition.</p>
        </div>

        <!-- Objectives -->
        <div class="mb-4">
          <h3>Objectives</h3>
          <ul>
            <li>Promote unity and professional development among Human Nutrition Students.</li>
            <li>Effectively represent and advocate for the ideas and prospects of Human Nutrition Students.</li>
            <li>Educate and serve the community by creating awareness, participating in research programs, and organizing academic and outreach activities.</li>
          </ul>
        </div>

        <!-- Core Values -->
        <div class="mb-4">
          <h3>Core Values</h3>
          <ol>
            <li>Inclusivity: We value diversity and inclusiveness, creating a welcoming and supportive community for all human nutrition students.</li>
            <li>Excellence: We aim to promote academic excellence and encourage students to reach their full potential in the field of human nutrition.</li>
            <li>Responsibility: We take our role in the community and the world seriously, acting with integrity, accountability, and a commitment to making a positive impact.</li>
            <li>Collaboration: We believe in the power of working together and value collaboration and teamwork to achieve our goals.</li>
            <li>Innovation: We embrace new ideas, approaches, and technologies, encouraging students to think creatively in the pursuit of new knowledge and better solutions.</li>
            <li>Community: We believe in the importance of community, dedicated to serving the needs of human nutrition students and the wider community through education and outreach initiatives.</li>
          </ol>
        </div>

        <!-- Religious Affiliation -->
        <div class="mb-4">
          <h3>Religious Affiliation</h3>
          <p>Makerere University Human Nutrition Students’ Association (MUHUNSA) does not discriminate against any member or prospective member based on religion. The association recognizes and respects the diversity of religious beliefs among its members and shall not promote or endorse any particular religion or religious doctrine. Members are free to exercise their religious beliefs, provided that such exercise does not interfere with the association's activities or conflict with its purpose.</p>
        </div>

      </div>
    </div>
  </main>

{% endblock %}

templates/bookmark.html
{% extends 'layout.html' %}

{% block title %}Bookmarks{% endblock %}

{% block body %}
<div class="container mt-5 mb-5">
  <div class="row">
    <h1 class="text-center mt-3 mb-3">
      Bookmarks
    </h1>
  </div>
  <div class="row row-cols-1 row-cols-md-3 g-4">
    {% for bookmark in bookmarks %}
      {% if bookmark.blog.is_active %}
        {% include 'card.html' with blog=bookmark.blog %}
      {% endif %}
    {% empty %}
      </div>
      <div class="row mt-5">
        <p class="text-center">
          Not bookmark any blog yet !!!
        </p>
    {% endfor %}
  </div>
  {% include 'pagination.html' with blogs=bookmarks %}
</div>
{% endblock %}

templates/card.html
<div class="col">
  <div class="card h-100">
    <div class="ratio ratio-16x9">
      <img src="{{ blog.thumbnail.url }}" class="card-img-top" alt="blog's thumbnail">
    </div>
    <div class="card-body">
      <h5 class="card-title">{{ blog.title }}</h5>
      <p class="card-text">{{ blog.desc|truncatechars:100 }}</p>
    </div>
    <div class="row justify-content-evenly mb-1">
      <div class="col-4">
        <p class="text-muted float-start">
          <i class="bi bi-eye"></i>
          {{ blog.views }}
        </p>
      </div>
      <div class="col-6">
        <p class="text-muted float-end">
          <i class="bi bi-clock-history"></i>
          {{ blog.published_on|timesince }}
        </p>
      </div>
    </div>
    <a class="btn btn-outline-primary w-100" href="{% url 'blogs:blog' blog.slug %}" role="button">Read More -></a>
  </div>
</div>

templates/category.html
{% extends 'layout.html' %}

{% block title %}Latest{% endblock %}

{% block body %}
{% endblock %}

templates/get_category.html
{% extends 'layout.html' %}

{% block title %}Latest{% endblock %}

{% block body %}
<div class="container mt-5 mb-5">
  <div class="row mb-5">
    <h2 class="text-center">{{ category.category }}</h2>
    <p>{{ category.desc }}</p>
  </div>
  <div class="row row-cols-1 row-cols-md-3 g-4">
    {% for blog in category.blogs.all %}
      {% if blog.is_active %}
        {% include "card.html" with blog=blog %}
      {% endif %}
    {% empty %}
      <p class="text-center">No blog found !!!</p>
    {% endfor %}
  </div>
</div>
{% endblock %}

templates/index.html
{% extends 'layout.html' %}
{% block title %}Index{% endblock %}
{% block body %}
<head>
   {% load static %}
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <!-- Bootstrap CSS -->
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
   <!-- Google Fonts -->
   <link rel="preconnect" href="https://fonts.googleapis.com">
   <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
   <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;300;400;700;900&display=swap" rel="stylesheet">
   <!-- Bootstrap CSS -->
   <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
   <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
   <link rel="stylesheet" href="{% static 'css/owl-carousel.css' %}">
   <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
   <link rel="stylesheet" href="{% static 'css/style.css' %}">
   <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
</head>
<body>
   <!-- Preloader -->
   <div class="preloader">
      <div class="loader">
         <div class="loader-outter"></div>
         <div class="loader-inner"></div>
         <div class="indicator">
            <svg width="16px" height="12px">
               <polyline id="back" points="1 6 4 6 6 11 10 1 12 6 15 6"></polyline>
               <polyline id="front" points="1 6 4 6 6 11 10 1 12 6 15 6"></polyline>
            </svg>
         </div>
      </div>
   </div>
   <!-- End Preloader -->
   <!--/ End Header Inner -->
   </header>
   <!-- End Header Area -->
   <!-- Slider Area -->
   <section class="slider">
      <div class="hero-slider">

         <!-- Start Single Slider -->
         <div class="single-slider">
             <div class="image-overlay" style="background-image: url('{% static 'img/v.jpg' %}')"></div>
            <div class="container">
               <div class="row">
                  <div class="col-lg-7">
                     <div class="text">
                        <h1>MAKERERE UNIVERSITY HUMAN NUTRITION STUDENTS' ASSOCIATION</h1>
                        <p><b>Promoting Nutrition Awareness.</b> <br><br>Provide a platform for academic,  professional and personal skill  development in nutrition to drive towards positive change through innovative thinking, practical skills to achieve a healthier and more sustainable world </p>
                        <p></p>
                        <div class="button">
                           <!-- <a href="#" class="btn">Join MUHUNSA</a> -->
                           <a href="{% url 'about_us' %}" class="btn primary">OUR STORY</a>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         <!-- End Single Slider -->

         <!-- Start Single Slider -->
         <div class="single-slider">
             <div class="image-overlay" style="background-image: url('{% static 'img/y.jpg' %}')"></div>
            <div class="container">
               <div class="row">
                  <div class="col-lg-7">
                     <div class="text">
                        <h1>Empowering Nutrition Leaders</h1>
                        <p>MUHUNSA is dedicated to community empowerment through comprehensive nutritional education. Engage with us in advocating the profound impact of proper nutrition on overall well-being, as we work together to cultivate a healthier and informed society. Join our mission to make nutritional knowledge accessible and impactful for everyone.</p>
                        <!-- <div class="button"> -->
                        <!-- <a href="#" class="btn">Get Appointment</a> -->
                        <!-- <a href="#" class="btn primary">About Us</a> -->
                        <!-- </div> -->
                     </div>
                  </div>
               </div>
            </div>
         </div>
         <!-- Start End Slider -->
         <!-- Start Single Slider -->
         <div class="single-slider">
             <div class="image-overlay" style="background-image: url('{% static 'img/z.jpg' %}')"></div>
            <div class="container">
               <div class="row">
                  <div class="col-lg-7">
                     <div class="text">
                        <h1>Connect with MUHUNSA</span></h1>
                        <p>Connect with nutrition enthusiasts and professionals. Together with MUHUNSA, let's build a healthier world.</p>
                        <div class="button">
                           <!-- <a href="#" class="btn">Get Appointment</a> -->
                           <a href="mailto:muhunsamakerereuniversity@gmail.com" class="btn">Contact Us</a>
                           <!--<a href="#" class="btn primary">Contact Now</a>-->
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         <!-- End Single Slider -->
      </div>
   </section>
   <!--/ End Slider Area -->
   <!-- Start Schedule Area -->
   <section class="schedule">
      <div class="container">
         <div class="schedule-inner">
            <div class="row">
               <div class="col-lg-4 col-md-6 col-12 ">

                  <!-- single-schedule -->
                  <div class="single-schedule first">
                     <div class="inner">
                        <div class="icon">
                           <!-- <i class="fa fa-ambulance"></i> -->
                        </div>
                        <div class="single-content">
                           <span class="text-center">CAPACITY BUILDING</span>
                           <!--<h4>Nutrient-Rich Options</h4>-->
                           <p>Explore resources aimed at enhancing knowledge, skills and practice aimed at improving nutrition related practices, policies and interventions</p>
                            <a href="#">LEARN MORE<i class="bi bi-arrow-right"></i></i></a>
                        </div>
                     </div>
                  </div>
               </div>
               <div class="col-lg-4 col-md-6 col-12">

                  <!-- single-schedule -->
                  <div class="single-schedule middle">
                     <div class="inner">
                        <div class="icon">
                           <!-- <i class="icofont-prescription"></i> -->
                        </div>
                        <div class="single-content">
                           <span class="text-center">DIET AND OVERALL WELLBEING</span>
                           <!--<h4>Nutrition Workshops</h4>-->
                           <p>Discover a wide range of information to enrich your nutritional knowledge and guide in making of informed choices about diet and overall health and well being</p>
                           <a href="#">LEARN MORE<i class="bi bi-arrow-right"></i></i></a>
                        </div>
                     </div>
                  </div>
               </div>
               <div class="col-lg-4 col-md-12 col-12">
                  <!-- single-schedule -->
                  <div class="single-schedule last">
                     <div class="inner">
                        <div class="icon">
                           <!-- <i class="icofont-ui-clock"></i> -->
                        </div>
                        <div class="single-content">
                           <span class="text-center">COLLABORATION</span>
                           <p>Discover the roles of the different industry players in addressing the different nutritional challenges for more effective interventions</p>
                           <br>
                           <!--<h4>Consultation Hours</h4>-->
                           <!--<ul class="time-sidual">-->
                           <!--   <li class="day">Monday - Friday <span>8.00-20.00</span></li>-->
                           <!--   <li class="day">Saturday <span>9.00-18.30</span></li>-->
                           <!--   <li class="day">Sunday <span>9.00-15.00</span></li>-->
                           <!--</ul>-->
                           <a href="#">LEARN MORE<i class="bi bi-arrow-right"></i></i></a>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </section>
   <script src="{% static 'js/jquery.min.js' %}"></script>
   <script src="{% static 'js/jquery-migrate-3.0.0.js' %}"></script>
   <script src="{% static 'js/slicknav.min.js' %}"></script>
   <script src="{% static 'js/owl-carousel.js' %}"></script>
   <script src="{% static 'js/main.js' %}"></script>
</body>
{% endblock %}

templates/latest.html
{% extends 'layout.html' %}

{% block title %}Latest{% endblock %}

{% block body %}
<div class="container mt-5 mb-5">
  <div class="row">
    <h1 class="text-center mt-3 mb-3">
      Latest Articles
    </h1>
  </div>
  <div class="row row-cols-1 row-cols-md-3 g-4">
    {% for blog in blogs %}
      {% include 'card.html' with blog=blog %}
    {% endfor %}
  </div>
  {% include 'pagination.html' with blogs=blogs %}
</div>
{% endblock %}

templates/layout.html
<!doctype html>
<html lang="en" data-bs-theme="dark">
<head>
  {% load static %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <meta property="og:title" content="{% block ogtitle %}MUHUNSA: MAKERERE UNIVERSITY HUMAN NUTRITION STUDENTS' ASSOCIATION{% endblock %}">
  <meta property="og:image" itemprop="image" content="{{ SITE_URL }}{% block ogimage %}{% static 'img/og.jpeg' %}{% endblock %}">
  <meta property="og:description" content="{% block ogdescription %}Empowering future nutrition leaders at Makerere University. MUHUNSA{% endblock %}">
  
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <link href="{% static 'css/index.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
  <title>{% block title %}{% endblock %} | MUHUNSA</title>
  <link rel="icon" href="{% static 'img/logo.jpeg' %}" type="image/x-icon">
</head>
<body>

<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <a class="navbar-brand" href="{% url 'index' %}">
      <img src="{% static 'img/logo.jpeg' %}" alt="Logo" width="30" height="30" class="d-inline-block align-text-top">
      MUHUNSA
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'index' %}">
            <i class="bi bi-house"></i>
            Home
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'latest' %}">
            <i class="bi bi-newspaper"></i>
            Articles
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'blogs:pubs' %}">
            <i class="bi bi-journal"></i>
            Publications
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'blogs:photo_gallery' %}">
            <i class="bi bi-images"></i>
            Gallery
          </a>
        </li>
        <form class="d-flex" role="search" action="{% url 'search' %}" method="get">
          <input class="form-control me-2" type="search" placeholder="Search article" aria-label="Search" name="query">
          <button class="btn btn-success" type="submit">
            <i class="bi bi-search"></i>
          </button>
        </form>
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'bookmark' %}">
            <i class="bi bi-bookmarks"></i>
            Bookmarks
          </a>
        </li>
        {% if request.user.is_author %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="bi bi-sliders"></i>
            Manage
          </a>
          <ul class="dropdown-menu">
            <li>
              <a class="dropdown-item" href="{% url 'manage:blog' %}">
                <i class="bi bi-book"></i>
                Blogs
              </a>
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'manage:category' %}">
                <i class="bi bi-grid"></i>
                Category
              </a>
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'manage:comment' %}">
                <i class="bi bi-chat-left-text"></i>
                Comment
              </a>
            </li>
          </ul>
        </li>
        {% endif %}
      </ul>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'accounts:logout' %}">
            <i class="bi bi-box-arrow-right"></i>
            Logout
          </a>
        </li>
      </ul>
      {% else %}
      </ul>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'accounts:login' %}">
            <i class="bi bi-box-arrow-in-right"></i>
              Login
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'accounts:register' %}">
              <i class="bi bi-person-add"></i>
            Register
          </a>
        </li>
      </ul>
      {% endif %}
    </div>
  </div>
</nav>

<!-- Messages -->
<div class="container" id="msg-box">
  {% if messages %}
  {% for message in messages %}
  <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
    <strong>{{ message.tags|upper }}</strong> {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
  {% endfor %}
  {% endif %}
</div>

{% block body %}{% endblock %}

  
<br><br>
{% block footer %}
<!-- Footer -->
<footer class="site-footer bg-dark text-white py-5">
  <div class="container">
    <div class="row">

      <div class="col-lg-4 col-md-6 mb-4 text-center">
        <h4 class="text-white mb-3">Makerere University Human Nutrition Students' Association (MUHUNSA)</h4>
        <p class="text-muted">Promoting the welfare and academic pursuits of students studying human nutrition at Makerere University's School of Food Technology, Nutrition and Bioengineering.</p>
        <p class="text-muted mb-4">Follow us on:</p>
        <ul class="list-inline social-icon">
          <li class="list-inline-item"><a href="https://www.linkedin.com/in/muhunsa-008b62282" class="social-icon-link bi-linkedin"></a></li>
          <li class="list-inline-item"><a href="https://www.twitter.com/Muhunsa_MAK" class="social-icon-link bi-twitter"></a></li>
          <li class="list-inline-item"><a href="https://www.instagram.com/muhunsa_MAK" class="social-icon-link bi-instagram"></a></li>
          <li class="list-inline-item"><a href="https://www.facebook.com/profile.php?id=100095493244693" class="social-icon-link bi-facebook"></a></li>
          <li class="list-inline-item"><a href="https://www.tiktok.com/@muhunsa_mak" class="social-icon-link bi-tiktok"></a></li>
        </ul>
      </div>

      <div class="col-lg-4 col-md-6 mb-4 text-center">
        <h5 class="text-white mb-3">Quick Links</h5>
        <ul class="list-unstyled footer-menu">
          <li class="footer-menu-item"><a href="{% url 'about_us' %}" class="footer-menu-link">About Us</a></li>
          <li class="footer-menu-item"><a href="#" class="footer-menu-link">Membership</a></li>
          <li class="footer-menu-item"><a href="#" class="footer-menu-link">Events</a></li>
          <li class="footer-menu-item"><a href="{% url 'blogs:pubs' %}" class="footer-menu-link">Resources</a></li>
          <li class="footer-menu-item"><a href="{% url 'blogs:photo_gallery' %}" class="footer-menu-link">Gallery</a></li>
        </ul>
      </div>

      <div class="col-lg-4 col-md-12 text-center">
        <h5 class="text-white mb-3">Contact Us</h5>
        <p class="text-muted mb-4">P.O. Box 7062,<br>Kampala, Uganda<br>Makerere University<br>College of Agricultural and Environmental Sciences<br>School of Food Technology, Nutrition and Bio-engineering<br>Department of Food Technology and Nutrition<br><a href="mailto:muhunsamakerereuniversity@gmail.com">Email : muhunsamakerereuniversity@gmail.com</a></p>
      </div>

    </div>
  </div>

  <div class="footer-bottom">
    <div class="container">
      <div class="row">
        <div class="col-12 text-center">
          <p class="copyright-text text-muted mb-0">© 2024 Makerere University Human Nutrition Students' Association (MUHUNSA). All rights reserved.</p>
        </div>
      </div>
    </div>
  </div>
</footer>
{% endblock %}



<!-- Javascripts -->
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
</body>
</html>

templates/popular.html
{% extends 'layout.html' %}

{% block title %}Trendings{% endblock %}

{% block body %}
<div class="container mt-5 mb-5">
  <div class="row">
    <h1 class="text-center mt-3 mb-3">Popular Blogs</h1>
  </div>
  <div class="row row-cols-1 row-cols-md-3 g-4">
    {% for blog in blogs %}
      {% include 'card.html' with blog=blog %}
    {% endfor %}
  </div>
  {% include 'pagination.html' with blogs=blogs %}
</div>
{% endblock %}

templates/search.html
{% extends 'layout.html' %}

{% block title %}{{ query }} - Search{% endblock %}

{% block body %}
<div class="container mt-5 mb-5">
  <div class="row">
    <h3>Search results for "{{ query }}"</h3>
  </div>
  <div class="row row-cols-1 row-cols-md-3 g-4">
    {% for blog in blogs %}
      {% include 'card.html' with blog=blog %}
    {% empty %}
    <p class="mt-5">No data found !!!<p>
    {% endfor %}
  </div>
  {% include 'pagination.html' with blogs=blogs %}
</div>
{% endblock %}